INSERT INTO dias (id, tipodia) VALUES (1, 'Soleado');
INSERT INTO dias (id, tipodia) VALUES (2, 'Nublado');
INSERT INTO dias (id, tipodia) VALUES (3, 'Lluvioso');
INSERT INTO dias (id, tipodia) VALUES (4, 'Nevado');
INSERT INTO dias (id, tipodia) VALUES (7, 'Niebla');
INSERT INTO dias (id, tipodia) VALUES (5, 'Tornado');
INSERT INTO dias (id, tipodia) VALUES (6, 'Ventisca');
INSERT INTO dias (id, tipodia) VALUES (8, 'Tsunami');

INSERT INTO localidades (id, nombre) VALUES (2, 'Madrid');
INSERT INTO localidades (id, nombre) VALUES (0, 'Getafe');
INSERT INTO localidades (id, nombre) VALUES (1, 'Alcala de Henares');
INSERT INTO localidades (id, nombre) VALUES (4, 'Mostoles');
INSERT INTO localidades (id, nombre) VALUES (5, 'Alcorcon');
INSERT INTO localidades (id, nombre) VALUES (3, 'Navacerrada');

INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (1, true, 'Getafe', 15, 20, 0, '2014-02-15', 'Soleado');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (2, false, 'Madrid', 10, 35, 50, '2008-10-23', 'Nublado');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (3, true, 'Madrid', 20, 20, 20, '2015-04-03', 'Soleado');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (4, true, 'Madrid', 20, 20, 20, '2015-04-03', 'Soleado');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (6, true, 'Navacerrada', 15, 30, 50, '2015-04-17', 'Tsunami');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (7, false, 'Alcala de Henares', 60, 0, 0, '2015-04-01', 'Ventisca');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (8, true, 'Alcala de Henares', 4, 25, 9, '2015-04-09', 'Tornado');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (9, true, 'Alcala de Henares', 4, 25, 9, '2015-04-09', 'Tornado');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (10, true, 'Mostoles', 51, 54, 52, '2015-04-15', 'Nevado');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (11, true, 'Mostoles', 54, 78, 65, '2015-04-16', 'Nublado');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (12, true, 'Madrid', 250, 54, 66, '2015-04-16', 'Nevado');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (13, true, 'Alcorcon', 45, 50, 50, '2015-04-01', 'Nevado');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (14, true, 'Mostoles', 45, 50, 45, '2015-04-16', 'Tsunami');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (15, true, 'Alcala de Henares', -15, 20, 20, '2015-04-08', 'Tornado');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (16, true, 'Navacerrada', -20, 35, 40, '2015-04-16', 'Ventisca');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (17, true, 'Getafe', -20, 30, 45, '2015-04-24', 'Niebla');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (18, true, 'Getafe', 50, 0, 20, '2015-04-02', 'Ventisca');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (19, true, 'Getafe', 35, 10, 50, '2015-04-02', 'Nevado');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (20, true, 'Getafe', -8, 65, 123, '2015-04-08', 'Lluvioso');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (21, true, 'Getafe', 100, 100, 100, '2015-04-24', 'Nevado');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (25, true, 'Navacerrada', -6, 20, 12, '2015-04-09', 'Nevado');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (26, false, 'Getafe', 89, 30, 12, '2015-04-16', 'Ventisca');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (27, true, 'Getafe', 85, 8, 12, '2015-04-25', 'Ventisca');
INSERT INTO datos (id, validado, localidad, temperatura, humedad, precipitacion, fecha, tipodia) VALUES (28, true, 'Alcala de Henares', -5, 15, 20, '2015-04-17', 'Nevado');
